import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { isMainModule, parseJsonText } from "../src/shared/cli.js";

type ArtifactJson = {
  abi: unknown[];
  bytecode?: string;
  contractName: string;
  sourceName: string;
};

const ARTIFACTS_ROOT = path.resolve(process.cwd(), "artifacts", "contracts");
const OUTPUT_PATH = path.resolve(process.cwd(), "src", "generated", "contracts.ts");

const CORE_PROTOCOL_CONTRACT_NAMES = [
  "AccessController",
  "ProtocolParameters",
  "ProtocolGovernanceToken",
  "ProtocolTimelock",
  "ProtocolGovernor",
  "ProtocolTreasury",
  "ResolutionModuleRegistry",
  "ClaimRegistry",
  "ArtifactRegistry",
  "BondEscrow",
  "AgentRegistry",
  "ReplicationRegistry",
  "ReputationCheckpointRegistry",
  "EpistemicMarket",
  "AppealsRegistry",
  "ClaimRewardVault",
] as const;

const RESOLUTION_MODULE_CONTRACT_NAMES = [
  "ComputationalResolutionModule",
  "BenchmarkResolutionModule",
  "WetLabResolutionModule",
] as const;

async function collectArtifactFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(root, entry.name);
      if (entry.isDirectory()) {
        return collectArtifactFiles(entryPath);
      }
      if (!entry.isFile() || !entry.name.endsWith(".json")) {
        return [];
      }
      return [entryPath];
    }),
  );

  return files.flat();
}

function toArtifactIdentifier(contractName: string): string {
  return `${contractName.charAt(0).toLowerCase()}${contractName.slice(1)}Artifact`;
}

function toJsonLiteral(value: unknown, indentLevel = 0): string {
  const indentation = "  ".repeat(indentLevel);
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : `${indentation}${line}`))
    .join("\n");
}

export async function generateContractArtifacts(): Promise<void> {
  const artifactFiles = await collectArtifactFiles(ARTIFACTS_ROOT);
  const artifacts = (
    await Promise.all(
      artifactFiles.map(async (filePath) => {
        const artifact = parseJsonText<ArtifactJson>(await readFile(filePath, "utf8"), filePath);
        return artifact;
      }),
    )
  ).sort((left, right) => {
    const leftKey = `${left.sourceName}:${left.contractName}`;
    const rightKey = `${right.sourceName}:${right.contractName}`;
    return leftKey.localeCompare(rightKey);
  });

  const deployableArtifacts = artifacts.filter(
    (artifact) =>
      (artifact.bytecode ?? "0x") !== "0x" && !artifact.sourceName.includes("/interfaces/"),
  );

  const artifactBlocks = artifacts.map((artifact) => {
    const identifier = toArtifactIdentifier(artifact.contractName);
    const serialized = toJsonLiteral(
      {
        contractName: artifact.contractName,
        sourceName: artifact.sourceName,
        abi: artifact.abi,
        bytecode: artifact.bytecode ?? "0x",
      },
      1,
    );

    return `export const ${identifier} = ${serialized} as const satisfies GeneratedContractArtifact;`;
  });

  const generatedMap = artifacts
    .map(
      (artifact) =>
        `  ${JSON.stringify(artifact.contractName)}: ${toArtifactIdentifier(artifact.contractName)},`,
    )
    .join("\n");

  const deployableMap = deployableArtifacts
    .map(
      (artifact) =>
        `  ${JSON.stringify(artifact.contractName)}: ${toArtifactIdentifier(artifact.contractName)},`,
    )
    .join("\n");

  const coreMap = CORE_PROTOCOL_CONTRACT_NAMES.map(
    (contractName) => `  ${JSON.stringify(contractName)}: ${toArtifactIdentifier(contractName)},`,
  ).join("\n");

  const moduleMap = RESOLUTION_MODULE_CONTRACT_NAMES.map(
    (contractName) => `  ${JSON.stringify(contractName)}: ${toArtifactIdentifier(contractName)},`,
  ).join("\n");

  const fileContents = `/* eslint-disable */
/**
 * Auto-generated by \`script/generate-contract-artifacts.ts\`.
 * Run \`npm run generate:contracts\` after recompiling contracts.
 */

export type GeneratedContractArtifact = {
  readonly contractName: string;
  readonly sourceName: string;
  readonly abi: readonly unknown[];
  readonly bytecode: string;
};

${artifactBlocks.join("\n\n")}

export const generatedContractArtifacts = {
${generatedMap}
} as const;

export const deployableContractArtifacts = {
${deployableMap}
} as const;

export const coreProtocolContractArtifacts = {
${coreMap}
} as const;

export const resolutionModuleContractArtifacts = {
${moduleMap}
} as const;

export type GeneratedContractName = keyof typeof generatedContractArtifacts;
export type DeployableContractName = keyof typeof deployableContractArtifacts;
export type CoreProtocolContractName = keyof typeof coreProtocolContractArtifacts;
export type ResolutionModuleContractName = keyof typeof resolutionModuleContractArtifacts;
`;

  await mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, fileContents);
}

if (isMainModule(import.meta.url)) {
  try {
    await generateContractArtifacts();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
